# When copied, remove this comment and update the ${} placeholders.

npmRegistries:
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_AUTH_TOKEN}
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: ${GH_AUTH_TOKEN}
  "https://registry.yarnpkg.com":
    npmAlwaysAuth: true
    npmAuthToken: ${GH_NPM_AUTH_TOKEN}

npmScopes:
  beefchimi:
    npmAlwaysAuth: true
    npmAuthToken: ${GH_AUTH_TOKEN}
    npmRegistryServer: "https://npm.pkg.github.com"
